### ISSUE TITLE
Format checking

### ISSUE THREAD

**Issue by urmichm** [Fischerfredl/flask-expects-json#24] opened 2022-07-17 20:25 UTC
Could you please provide an example of Format checking usage?

I see there was another issue regarding this issue [here](https://github.com/Fischerfredl/flask-expects-json/issues/22)

Would you mind providing the proper syntax needed to apply here?

**Comment by Fischerfredl** [comment] 2022-07-18 07:03
Duplicate of #22

**Closed as not planned by Fischerfredl** 2022-07-18 07:03 UTC
